-----------------------------------------------------------------------------
-- Assessment Service DDL
-----------------------------------------------------------------------------

CREATE INDEX SAM_ASMNTGRDNG_PID_AGENT_I ON SAM_ASSESSMENTGRADING_T
(
       PUBLISHEDASSESSMENTID			ASC,
       AGENTID							ASC,
	   FORGRADE                         ASC
);

CREATE INDEX SAM_ITEMGRADING_AG_PI_I ON SAM_ITEMGRADING_T
(
       ASSESSMENTGRADINGID				ASC,
       PUBLISHEDITEMID					ASC
);

CREATE INDEX SAM_PUBLISHEDITEMMETADATA_IL_I ON SAM_PUBLISHEDITEMMETADATA_T
(
	ITEMID								ASC,
	LABEL								ASC
);

CREATE INDEX SAM_PUBLISHEDITEMFEEDBACK_IT_I ON SAM_PUBLISHEDITEMFEEDBACK_T
(
	ITEMID								ASC,
	TYPEID								ASC
);

CREATE INDEX SAM_PUBSECTIONMETADATA_IT_I ON SAM_PUBLISHEDSECTIONMETADATA_T
(
	SECTIONID							ASC,
	LABEL								ASC
);
